Fix unaligned memory access when reading DRM events
Running with debug assertions enabled on armv7 (an stm32mp157) panics
due to unaligned memory reads:

thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0xbec90b44', .../drm-0.9.0/src/control/mod.rs:906:34

Fix this by using the corresponding functions from core to safely
copy the data (in C we'd do a memcpy).